name: Check homebrew recipe and modify versions

on:
  schedule:
    - cron: "0 */12 * * *"
  push:
    paths:
      - '.github/workflows/update_recipe.yml'
  workflow_dispatch:

jobs:
  checkupdate:
    runs-on: ubuntu-latest
    env:
      RECIPE: Formula/conveyor.rb
    steps:
    - name: Check out repo
      uses: actions/checkout@v4

    - name: Check latest version
      id: latest
      run: echo "version=$(curl -s https://app.datafy.cloud/api/info/cli/version)" >> $GITHUB_OUTPUT

    - name: Check current version
      id: current
      run: echo "version=$(grep 'version \".*\"' $RECIPE | grep -o '[0-9]*\.[0-9]*.[0-9]*')" >> $GITHUB_OUTPUT

    - name: Modify recipe if they are different
      if: steps.latest.outputs.version != steps.current.outputs.version
      run: |
        python3 release.py --noninteractive

    - name: Trigger a pull request
      if: steps.latest.outputs.version != steps.current.outputs.version
      uses: peter-evans/create-pull-request@v6
      with:
        commit-message: Updated from version ${{ steps.current.outputs.version }} to ${{ steps.latest.outputs.version }}
        author: 'github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>'
